// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SFCDashboard.Data;

#nullable disable

namespace SFCDashboard.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250703033931_initialMigration")]
    partial class initialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AreaNetworkEngineer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EngineerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AreaNetworkEngineers");
                });

            modelBuilder.Entity("Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ProjectPEMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PlannedEventId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlannedEventId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectPEMappings");
                });

            modelBuilder.Entity("SFCDB.Models.PERecord", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ACCESS_MEDIUM")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ACCESS_MEDIUM");

                    b.Property<string>("ACCESS_MEDIUM_A_END")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ACCESS_MEDIUM_A_END");

                    b.Property<string>("ACCESS_MEDIUM_B_END")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ACCESS_MEDIUM_B_END");

                    b.Property<string>("ACCOUNT_MANAGER")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ACCOUNT_MANAGER");

                    b.Property<string>("CCT_ID")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CCT_ID");

                    b.Property<string>("CONTRACTOR_NAME")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CONTRACTOR_NAME");

                    b.Property<string>("CRM_ORDER")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CRM_ORDER");

                    b.Property<string>("CUSTOMER")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CUSTOMER");

                    b.Property<string>("CUS_TYPE")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CUS_TYPE");

                    b.Property<string>("FIBER_PE_NO")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FIBER_PE_NO");

                    b.Property<string>("FIBER_PE_TASK_NAME")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FIBER_PE_TASK_NAME");

                    b.Property<string>("FIBER_PE_TASK_WG")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FIBER_PE_TASK_WG");

                    b.Property<string>("FIBER_SO_ID")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FIBER_SO_ID");

                    b.Property<string>("JOB_REFERENCE")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("JOB_REFERENCE");

                    b.Property<string>("LEA")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LEA");

                    b.Property<string>("LOCATION_A_ADDRESS")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LOCATION_A_ADDRESS");

                    b.Property<string>("LOCATION_B_ADDRESS")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LOCATION_B_ADDRESS");

                    b.Property<string>("NTU_TYPE")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NTU_TYPE");

                    b.Property<string>("ORDER_TYPE")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ORDER_TYPE");

                    b.Property<string>("PENDING_TASK_NAME")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PENDING_TASK_NAME");

                    b.Property<string>("PENDING_WG")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PENDING_WG");

                    b.Property<string>("PE_ACTIVITY")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PE_ACTIVITY");

                    b.Property<string>("PE_AREA")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PE_AREA");

                    b.Property<string>("PE_NATURE")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PE_NATURE");

                    b.Property<string>("PE_NUMBER")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PE_NUMBER");

                    b.Property<string>("PE_OBJECTIVE")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PE_OBJECTIVE");

                    b.Property<string>("PE_TITLE")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PE_TITLE");

                    b.Property<string>("PE_WO_COMMENTS")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PE_WO_COMMENTS");

                    b.Property<string>("PRODUCT_SO_ID")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PRODUCT_SO_ID");

                    b.Property<string>("PROVINCE")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PROVINCE");

                    b.Property<string>("PROVINCE_1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PROVINCE_1");

                    b.Property<string>("REGION")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("REGION");

                    b.Property<string>("REGION_1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("REGION_1");

                    b.Property<string>("REQUEST_REFERENCE_NO")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("REQUEST_REFERENCE_NO");

                    b.Property<string>("RTOM")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RTOM");

                    b.Property<string>("RTOM_1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RTOM_1");

                    b.Property<string>("RTOM_DESCRIPTION")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RTOM_DESCRIPTION");

                    b.Property<string>("SECTION_HANDLED_BY")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SECTION_HANDLED_BY");

                    b.Property<string>("SERVICE_CATEGORY")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SERVICE_CATEGORY");

                    b.Property<DateTime?>("SERVICE_REQUIRED_DATE")
                        .HasColumnType("datetime2")
                        .HasColumnName("SERVICE_REQUIRED_DATE");

                    b.Property<string>("SERVICE_SPEED")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SERVICE_SPEED");

                    b.Property<string>("SERVICE_TYPE")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SERVICE_TYPE");

                    b.Property<DateTime?>("SO_CREATE_DATE")
                        .HasColumnType("datetime2")
                        .HasColumnName("SO_CREATE_DATE");

                    b.Property<string>("SO_ID")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SO_ID");

                    b.Property<string>("SO_NUMBER")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SO_NUMBER");

                    b.Property<string>("TASK_NAME")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TASK_NAME");

                    b.Property<int?>("TASK_SEQ")
                        .HasColumnType("int")
                        .HasColumnName("TASK_SEQ");

                    b.Property<string>("TASK_WG")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TASK_WG");

                    b.Property<string>("WO_ACTUAL_START_DATE")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("WO_ACTUAL_START_DATE");

                    b.Property<string>("WO_COMMENTS")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("WO_COMMENTS");

                    b.Property<string>("WO_ID")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("WO_ID");

                    b.Property<DateTime?>("WO_START_DATE")
                        .HasColumnType("datetime2")
                        .HasColumnName("WO_START_DATE");

                    b.Property<string>("WO_STATUS")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("WO_STATUS");

                    b.HasKey("ID");

                    b.ToTable("PERecords", (string)null);
                });

            modelBuilder.Entity("SFCDB.Models.UrgentReason", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("PERecordID")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("PERecordID");

                    b.ToTable("UrgentReasons");
                });

            modelBuilder.Entity("SFCDashboard.Models.BOQ", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AccessoriesRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AccessoriesTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AdjustedUnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<decimal>("MainMaterialRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MainMaterialTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("P0Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("P1Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("P2Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ServicesOHTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ServicesOverheadRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<int>("UDNameId")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("SubCategoryId");

                    b.HasIndex("TaskId");

                    b.HasIndex("UDNameId");

                    b.ToTable("BOQs");
                });

            modelBuilder.Entity("SFCDashboard.Models.ContractorNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContractorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PENumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("RelatedActivityId")
                        .HasColumnType("int");

                    b.Property<int?>("RelatedTaskId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RelatedActivityId");

                    b.HasIndex("RelatedTaskId");

                    b.ToTable("ContractorNotifications");
                });

            modelBuilder.Entity("SFCDashboard.Models.Escalation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IgnoreReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("IgnoredAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IgnoredById")
                        .HasColumnType("int");

                    b.Property<bool>("IsIgnored")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int?>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlannedEventId")
                        .HasColumnType("int");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IgnoredById");

                    b.HasIndex("PlannedEventId");

                    b.HasIndex("TaskId");

                    b.ToTable("Escalations");
                });

            modelBuilder.Entity("SFCDashboard.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PlannedEventId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlannedEventId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("SFCDashboard.Models.PEIssue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachmentPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsHiddenFromInbox")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReminder")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReply")
                        .HasColumnType("bit");

                    b.Property<bool>("IsResolutionRequest")
                        .HasColumnType("bit");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit");

                    b.Property<string>("IssueText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OriginalIssueId")
                        .HasColumnType("int");

                    b.Property<int>("PETaskId")
                        .HasColumnType("int");

                    b.Property<int>("PlannedEventId")
                        .HasColumnType("int");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PEIssues");
                });

            modelBuilder.Entity("SFCDashboard.Models.PEIssueResolution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ConfirmationRequestedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ConfirmedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("IssueId")
                        .HasColumnType("int");

                    b.Property<int>("PlannedEventId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ResolutionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResolutionDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.HasIndex("PlannedEventId");

                    b.ToTable("PEIssueResolutions");
                });

            modelBuilder.Entity("SFCDashboard.Models.PETask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ACtualTaskCompleteDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActualTaskCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EscalationsDisabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("EstimatedTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsOLAViolate")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUrgent")
                        .HasColumnType("bit");

                    b.Property<string>("OLA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OLADateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PENumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Priority")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Task")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TaskCompleteDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TaskCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TaskSeq")
                        .HasColumnType("int");

                    b.Property<string>("TaskStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaskWorkGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UrgentMarkedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("UrgentRequested")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ViolationStartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PENumber");

                    b.ToTable("PETasks");
                });

            modelBuilder.Entity("SFCDashboard.Models.PETaskList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OLA_Parameters")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaskSeq")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PETaskList");
                });

            modelBuilder.Entity("SFCDashboard.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Can manage estimated time for tasks",
                            Name = "CanManageEstimatedTime"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Can send \"Planned Event\" urgent requests",
                            Name = "CanSendPEUrgentRequests"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Can view and accept Planned Event urgent requests",
                            Name = "CanAcceptUrgentRequests"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Can mark a \"Task\" of a specific PE as Urgent",
                            Name = "CanMakeTasksUrgent"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Admin permissions",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Can view all records",
                            Name = "ViewAll"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Can report issues on Planned Events",
                            Name = "CanReportIssues"
                        });
                });

            modelBuilder.Entity("SFCDashboard.Models.PlannedEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessMedium")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ACCESS_MEDIUM");

                    b.Property<string>("AccessMediumAEnd")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ACCESS_MEDIUM_A_END");

                    b.Property<string>("AccessMediumBEnd")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ACCESS_MEDIUM_B_END");

                    b.Property<string>("AccountManager")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ACCOUNT_MANAGER");

                    b.Property<string>("CctId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CCT_ID");

                    b.Property<string>("ContractorName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CONTRACTOR_NAME");

                    b.Property<DateTime?>("CreatedDateFromPE")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDateFromPE");

                    b.Property<string>("CrmOrder")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CRM_ORDER");

                    b.Property<string>("CusType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CUS_TYPE");

                    b.Property<string>("Customer")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CUSTOMER");

                    b.Property<string>("FiberPeNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FIBER_PE_NO");

                    b.Property<string>("FiberPeTaskName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FIBER_PE_TASK_NAME");

                    b.Property<string>("FiberPeTaskWg")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FIBER_PE_TASK_WG");

                    b.Property<string>("FiberSoId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FIBER_SO_ID");

                    b.Property<bool>("IsHold")
                        .HasColumnType("bit");

                    b.Property<string>("JobReference")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("JOB_REFERENCE");

                    b.Property<string>("Lea")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LEA");

                    b.Property<string>("LocationAAddress")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LOCATION_A_ADDRESS");

                    b.Property<string>("LocationBAddress")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LOCATION_B_ADDRESS");

                    b.Property<string>("NtuType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NTU_TYPE");

                    b.Property<string>("OrderType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ORDER_TYPE");

                    b.Property<DateTime>("PECreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("PE_CREATED_DATE");

                    b.Property<string>("PEStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PE_STATUS");

                    b.Property<string>("PeActivity")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PE_ACTIVITY");

                    b.Property<string>("PeArea")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PE_AREA");

                    b.Property<string>("PeNature")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PE_NATURE");

                    b.Property<string>("PeNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("PE_NUMBER");

                    b.Property<string>("PeObjective")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PE_OBJECTIVE");

                    b.Property<string>("PeTitle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PE_TITLE");

                    b.Property<string>("PeWoComments")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PE_WO_COMMENTS");

                    b.Property<string>("PendingTaskName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PENDING_TASK_NAME");

                    b.Property<string>("PendingWg")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PENDING_WG");

                    b.Property<string>("Priority")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PRIORITY");

                    b.Property<string>("ProductSoId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PRODUCT_SO_ID");

                    b.Property<string>("Province")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PROVINCE");

                    b.Property<string>("Province1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PROVINCE_1");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("REGION");

                    b.Property<string>("Region1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("REGION_1");

                    b.Property<string>("RequestReferenceNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("REQUEST_REFERENCE_NO");

                    b.Property<string>("Rtom")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RTOM");

                    b.Property<string>("Rtom1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RTOM_1");

                    b.Property<string>("RtomDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RTOM_DESCRIPTION");

                    b.Property<string>("SectionHandledBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SECTION_HANDLED_BY");

                    b.Property<string>("ServiceCategory")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SERVICE_CATEGORY");

                    b.Property<DateTime?>("ServiceRequiredDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("SERVICE_REQUIRED_DATE");

                    b.Property<string>("ServiceSpeed")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SERVICE_SPEED");

                    b.Property<string>("ServiceType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SERVICE_TYPE");

                    b.Property<DateTime?>("SoCreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("SO_CREATE_DATE");

                    b.Property<string>("SoId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SO_ID");

                    b.Property<string>("SoNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SO_NUMBER");

                    b.Property<int?>("SystemUserId")
                        .HasColumnType("int");

                    b.Property<string>("TaskName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TASK_NAME");

                    b.Property<int?>("TaskSeq")
                        .HasColumnType("int")
                        .HasColumnName("TASK_SEQ");

                    b.Property<string>("TaskWg")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TASK_WG");

                    b.Property<int?>("UrgentRequestedById")
                        .HasColumnType("int");

                    b.Property<string>("UrgentRequestedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WoActualStartDate")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("WO_ACTUAL_START_DATE");

                    b.Property<string>("WoComments")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("WO_COMMENTS");

                    b.Property<string>("WoId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("WO_ID");

                    b.Property<DateTime?>("WoStartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("WO_START_DATE");

                    b.Property<string>("WoStatus")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("WO_STATUS");

                    b.Property<int?>("WorkGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SystemUserId");

                    b.HasIndex("WorkGroupId");

                    b.ToTable("PlannedEvents");
                });

            modelBuilder.Entity("SFCDashboard.Models.RTOMWeight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RTOM")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("RTOMWeights");
                });

            modelBuilder.Entity("SFCDashboard.Models.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("SFCDashboard.Models.SubTaskList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Frequency")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastReported")
                        .HasColumnType("datetime2");

                    b.Property<int>("PETaskListId")
                        .HasColumnType("int");

                    b.Property<string>("SubTaskName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("PETaskListId");

                    b.ToTable("SubTaskLists");
                });

            modelBuilder.Entity("SFCDashboard.Models.SurveyTaskActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PETaskId")
                        .HasColumnType("int");

                    b.Property<int>("SystemUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PETaskId");

                    b.HasIndex("SystemUserId");

                    b.ToTable("SurveyTaskActivities");
                });

            modelBuilder.Entity("SFCDashboard.Models.SystemConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfigKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfigValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SystemConfigurations");
                });

            modelBuilder.Entity("SFCDashboard.Models.TaskEstimationHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EstimatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskEstimationHistory");
                });

            modelBuilder.Entity("SFCDashboard.Models.TaskExtensionRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovalTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedById")
                        .HasColumnType("int");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("Justification")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PlannedEventId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequestedById")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("RequestedExtension")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedById");

                    b.HasIndex("PlannedEventId");

                    b.HasIndex("RequestedById");

                    b.ToTable("TaskExtensionRequests");
                });

            modelBuilder.Entity("SFCDashboard.Models.TaskHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangeTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Comments")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NewStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PlannedEventId")
                        .HasColumnType("int");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlannedEventId");

                    b.HasIndex("UserId");

                    b.ToTable("TaskHistories");
                });

            modelBuilder.Entity("SFCDashboard.Models.UDCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("UDCategories");
                });

            modelBuilder.Entity("SFCDashboard.Models.UDName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("UDNames");
                });

            modelBuilder.Entity("SFCDashboard.Models.UDSubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("SubCategory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("UDSubCategories");
                });

            modelBuilder.Entity("SFCDashboard.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("SFCDashboard.Models.UserWorkGroup", b =>
                {
                    b.Property<int>("SystemUserId")
                        .HasColumnType("int");

                    b.Property<int>("WorkGroupId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("SystemUserId", "WorkGroupId");

                    b.HasIndex("WorkGroupId");

                    b.ToTable("UserWorkGroups");
                });

            modelBuilder.Entity("SFCDashboard.Models.WorkGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("WorkGroups");
                });

            modelBuilder.Entity("SystemUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UserRoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserRoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ProjectPEMapping", b =>
                {
                    b.HasOne("SFCDashboard.Models.PlannedEvent", "PlannedEvent")
                        .WithMany()
                        .HasForeignKey("PlannedEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project", "Project")
                        .WithMany("ProjectPEs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlannedEvent");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SFCDB.Models.UrgentReason", b =>
                {
                    b.HasOne("SFCDB.Models.PERecord", "PERecord")
                        .WithMany()
                        .HasForeignKey("PERecordID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PERecord");
                });

            modelBuilder.Entity("SFCDashboard.Models.BOQ", b =>
                {
                    b.HasOne("SFCDashboard.Models.UDCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SystemUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SFCDashboard.Models.UDSubCategory", "SubCategory")
                        .WithMany()
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SFCDashboard.Models.PETask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SFCDashboard.Models.UDName", "UDName")
                        .WithMany()
                        .HasForeignKey("UDNameId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("CreatedBy");

                    b.Navigation("SubCategory");

                    b.Navigation("Task");

                    b.Navigation("UDName");
                });

            modelBuilder.Entity("SFCDashboard.Models.ContractorNotification", b =>
                {
                    b.HasOne("SFCDashboard.Models.SurveyTaskActivity", "RelatedActivity")
                        .WithMany()
                        .HasForeignKey("RelatedActivityId");

                    b.HasOne("SFCDashboard.Models.PETask", "RelatedTask")
                        .WithMany()
                        .HasForeignKey("RelatedTaskId");

                    b.Navigation("RelatedActivity");

                    b.Navigation("RelatedTask");
                });

            modelBuilder.Entity("SFCDashboard.Models.Escalation", b =>
                {
                    b.HasOne("SystemUser", "IgnoredBy")
                        .WithMany()
                        .HasForeignKey("IgnoredById");

                    b.HasOne("SFCDashboard.Models.PlannedEvent", null)
                        .WithMany("Escalations")
                        .HasForeignKey("PlannedEventId");

                    b.HasOne("SFCDashboard.Models.PETask", "PETask")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IgnoredBy");

                    b.Navigation("PETask");
                });

            modelBuilder.Entity("SFCDashboard.Models.Notification", b =>
                {
                    b.HasOne("SFCDashboard.Models.PlannedEvent", "PlannedEvent")
                        .WithMany()
                        .HasForeignKey("PlannedEventId");

                    b.HasOne("SystemUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("PlannedEvent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SFCDashboard.Models.PEIssueResolution", b =>
                {
                    b.HasOne("SFCDashboard.Models.PEIssue", "Issue")
                        .WithMany()
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SFCDashboard.Models.PlannedEvent", "PlannedEvent")
                        .WithMany()
                        .HasForeignKey("PlannedEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");

                    b.Navigation("PlannedEvent");
                });

            modelBuilder.Entity("SFCDashboard.Models.PETask", b =>
                {
                    b.HasOne("SFCDashboard.Models.PlannedEvent", "PlannedEvent")
                        .WithMany()
                        .HasForeignKey("PENumber")
                        .HasPrincipalKey("PeNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlannedEvent");
                });

            modelBuilder.Entity("SFCDashboard.Models.PlannedEvent", b =>
                {
                    b.HasOne("SystemUser", null)
                        .WithMany("AssignedEvents")
                        .HasForeignKey("SystemUserId");

                    b.HasOne("SFCDashboard.Models.WorkGroup", null)
                        .WithMany("AssignedEvents")
                        .HasForeignKey("WorkGroupId");
                });

            modelBuilder.Entity("SFCDashboard.Models.RolePermission", b =>
                {
                    b.HasOne("SFCDashboard.Models.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SFCDashboard.Models.UserRole", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SFCDashboard.Models.SubTaskList", b =>
                {
                    b.HasOne("SFCDashboard.Models.PETaskList", "PETaskList")
                        .WithMany()
                        .HasForeignKey("PETaskListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PETaskList");
                });

            modelBuilder.Entity("SFCDashboard.Models.SurveyTaskActivity", b =>
                {
                    b.HasOne("SFCDashboard.Models.PETask", "PETask")
                        .WithMany()
                        .HasForeignKey("PETaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SystemUser", "User")
                        .WithMany()
                        .HasForeignKey("SystemUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PETask");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SFCDashboard.Models.TaskEstimationHistory", b =>
                {
                    b.HasOne("SFCDashboard.Models.PETask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("SFCDashboard.Models.TaskExtensionRequest", b =>
                {
                    b.HasOne("SystemUser", "ApprovedBy")
                        .WithMany("ApprovedExtensions")
                        .HasForeignKey("ApprovedById");

                    b.HasOne("SFCDashboard.Models.PlannedEvent", "PlannedEvent")
                        .WithMany()
                        .HasForeignKey("PlannedEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SystemUser", "RequestedBy")
                        .WithMany("RequestedExtensions")
                        .HasForeignKey("RequestedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedBy");

                    b.Navigation("PlannedEvent");

                    b.Navigation("RequestedBy");
                });

            modelBuilder.Entity("SFCDashboard.Models.TaskHistory", b =>
                {
                    b.HasOne("SFCDashboard.Models.PlannedEvent", "PlannedEvent")
                        .WithMany()
                        .HasForeignKey("PlannedEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SystemUser", "ChangedBy")
                        .WithMany("TaskChanges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedBy");

                    b.Navigation("PlannedEvent");
                });

            modelBuilder.Entity("SFCDashboard.Models.UDName", b =>
                {
                    b.HasOne("SFCDashboard.Models.UDCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SFCDashboard.Models.UDSubCategory", "SubCategory")
                        .WithMany()
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("SFCDashboard.Models.UDSubCategory", b =>
                {
                    b.HasOne("SFCDashboard.Models.UDCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SFCDashboard.Models.UserWorkGroup", b =>
                {
                    b.HasOne("SystemUser", "SystemUser")
                        .WithMany("UserWorkGroups")
                        .HasForeignKey("SystemUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SFCDashboard.Models.WorkGroup", "WorkGroup")
                        .WithMany("UserWorkGroups")
                        .HasForeignKey("WorkGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemUser");

                    b.Navigation("WorkGroup");
                });

            modelBuilder.Entity("SystemUser", b =>
                {
                    b.HasOne("SFCDashboard.Models.UserRole", "UserRole")
                        .WithMany()
                        .HasForeignKey("UserRoleId");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("Project", b =>
                {
                    b.Navigation("ProjectPEs");
                });

            modelBuilder.Entity("SFCDashboard.Models.PlannedEvent", b =>
                {
                    b.Navigation("Escalations");
                });

            modelBuilder.Entity("SFCDashboard.Models.UserRole", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("SFCDashboard.Models.WorkGroup", b =>
                {
                    b.Navigation("AssignedEvents");

                    b.Navigation("UserWorkGroups");
                });

            modelBuilder.Entity("SystemUser", b =>
                {
                    b.Navigation("ApprovedExtensions");

                    b.Navigation("AssignedEvents");

                    b.Navigation("RequestedExtensions");

                    b.Navigation("TaskChanges");

                    b.Navigation("UserWorkGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
